import aurelien_gb from "@/public/assets/testimonials/aurelien-gh.jpg";

export const testimonials = [
    {
        client_img: aurelien_gb,
        type: "image",
        name: "Hamid Boroumandian",
        title: "CEO, Axya Inc.",
        text: "Add-in Expert delivered his work with good quality and was very supportive throughout the whole process. He was generally available and communicated well with me and the BE team to integrate the application. The approval process for the application in the app store could have been smoother but overall I am pleased and will work with Add-in Expert in the future on similar projects.",
    },
    {
        client_img: "",
        type: "avatar",
        name: "Mr. Stevo",
        title: "United Kingdom",
        text: "I had an excellent experience working with Aamir on a complex Microsoft Word add-in project. From the beginning, Aamir was communicative and highly responsive, always eager to understand my requirements in detail. He consistently kept me updated on his progress and was quick to implement changes, even providing video demos to make sure everything was on track. Despite the technical challenges, Aamir showed great flexibility and went above and beyond to troubleshoot compatibility issues, even offering discounted rates as our collaboration continued. His dedication and professionalism were evident in every interaction, and his expertise with Microsoft Word made a big difference. Looking forward to working with Aamir again on future projects – highly recommended!",
    },
    {
        client_img: "",
        client_avatar: "SC",
        type: "string",
        name: "Smith Caz",
        title: "New York, USA",
        text: "Add-in Expert is very good at implementing coding according to our wishes, besides that he explains clearly and patiently. Response speed and service are very satisfying",
    },
    {
        client_img: "",
        client_avatar: "TP",
        type: "string",
        name: "Tom Palmer",
        title: "United Kindom",
        text: "Add-in Expert is a very reliable guy and I will continue to use him for my projects. Helpful and takes the time to understand. Would definitely recommend",
    },
    {
        client_img: "",
        type: "avatar",
        name: "Adam New",
        title: "United Kindom",
        text: "Very easy to work with. Understood requirements very quickly and worked with an unfamilar database easily. Communication was excellent",
    },
    {
        client_img: "",
        client_avatar: "JD",
        type: "string",
        name: "Qcompany",
        title: "Netherlands",
        text: "Clear and good communication and wiling to think out of the box. Project scope changed during the project but this was no problem and we got to a final deliverable",
    },
    {
        client_img: "",
        client_avatar: "JD",
        type: "string",
        name: "Joey Dean",
        title: "United States",
        text: "Great experience! Documented and executed requirements appropriately",
    },
    {
        client_img: "",
        client_avatar: "NS",
        type: "string",
        name: "Mr. Ntislkl",
        title: "United States",
        text: "Great job. Completed exactly as requested. Quick responses from seller. Will request again.",
    },
    {
        client_img: "",
        client_avatar: "TP",
        type: "string",
        name: "Tom Palmer",
        title: "United Kindom",
        text: "This guy really wants to please! He did everything perfectly and we have a very exciting and unique product. Top marks",
    },
    {
        client_img: "",
        client_avatar: "KH",
        type: "string",
        name: "Kieran Harland",
        title: "State Library of New South Wales",
        text: "Add-in Expert is the best in the business Could not recommend someone more Listened to everything I wanted but helped me build on my original idea as well I would give 10 stars if I could.",
    },
    {
        client_img: "",
        client_avatar: "TP",
        type: "string",
        name: "Tom Palmer",
        title: "United Kindom",
        text: "I really hope to work with this guy for a long time. absolutely wonderful service, knowledge, end product and attitude",
    },
    {
        client_img: "",
        client_avatar: "AD",
        type: "string",
        name: "Ashley Deverell",
        title: "United States",
        text: "Was good at finding solutions, what i wanted was not possible so he though along with me to come up with an alternative solution",
    }
];
